name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

resources:
  containers:
    - container: postgres
      image: postgres:latest
      ports:
      - 5432:5432
      env:
        POSTGRES_DB: $(QIYANNA_CONFIG_DATABASE_USERNAME)
        POSTGRES_USER: $(QIYANNA_CONFIG_DATABASE_USERNAME)
        POSTGRES_PASSWORD: $(QIYANNA_CONFIG_DATABASE_PASSWORD)
    - container: mongo
      image: mongo:latest

services:
  postgres: postgres
  mongo: mongo


variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$(Pipeline.Workspace)/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS_TEST: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true -DargLine=-Dspring.profiles.active=test"

steps:
- task: CacheBeta@0
  inputs:
    key: maven | **/pom.xml
    path: $(Pipeline.Workspace)/.m2/repository
  displayName: Cache Maven local repo

- script: mvn install -B -e
- task: Maven@3
  displayName: Test compile
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'test-compile'
    options: $(MAVEN_CLI_OPTS_TEST)
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    checkStyleRunAnalysis: true
    pmdRunAnalysis: true
    findBugsRunAnalysis: true

- task: Maven@3
  displayName: Run test
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'test'
    options: $(MAVEN_CLI_OPTS_TEST)
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    checkStyleRunAnalysis: true
    pmdRunAnalysis: true
    findBugsRunAnalysis: true
