version: '3'
services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
  postgres:
    image: postgres:11.5-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: qiyanna
      POSTGRES_USER: qiyanna
      POSTGRES_PASSWORD: qiyanna123
    ports:
      - "54320:5432"